firstpro/urls.py
import imp
from unicodedata import name
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from pages.views import *

from products.views import *

from customer.views import *
from owner.views import *

from cart.views import *

from checkout.views import *

from notification.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),

    path('register/', registration_view, name='register'),
    # path('activate/<uidb46>/<token>', activate, name='activate'),
    path('', homepage_view, name='home'),
    path('contact/', contact, name='contact'),
    path('product/<int:id>/', product_view, name='product'),
    path('product-by-category/<str:choice>/',
         product_category_view, name='product-by-category'),
     path('product-by-subcategory/<str:subcategory>/',
         product_sub_category_view, name='product-by-subcategory'),
    path('cart/', cart_view, name='cart'),

    path('owner/', admin_view, name='owner'),
    path('owner-orders/', admin_order_view, name='owner-orders'),
    path('owner/delete-orders/<int:pk>',
         delete_shipping_order, name='delete-orders'),
    path('manage-customer/', manageCustomer, name='manage-customer'),
    path('update-customer/<int:pk>/', updateCustomer, name='update-customer'),
    path('delete-customer/<int:pk>/', deleteCustomer, name='delete-customer'),
    path('manage-product/', manageProduct, name='manage-product'),
    path('update-product/<int:pk>/', updateProduct, name='update-product'),
    path('delete-product/<int:pk>/', deleteProduct, name='delete-product'),
    path('create-order', createOrder,  name='create-order'),
    path('update-order/<int:pk>/', updateOrder, name='update-order'),

    path('checkout/', checkout_view, name='checkout'),
    path('update-cart/', update_data_view, name='update-cart'),
    path('process-checkout/', processCheckout, name='process-checkout'),
    path('search/', searchProducts, name='search'),

    path('create-product', create_products_view, name='create-product'),



    path('logout/', logoutUser, name='logout'),
    path('update-discount/', update_discount_view, name='update-discount'),
    path('root/', rootpage, name="rootpage"),
    path('contact/', contact, name="contact"),
    path('aboutus/', aboutus, name='aboutus' ),
     path('helppage/', helppage, name='helppage' ),
    path('user-profile/', user_profile_view, name='user-profile'),
    path('delete-account/<int:pk>/', delete_account, name='delete-account'),
  
    path('change-password/<int:pk>/', changePassword, name='change-password'),
    path('update-account/<int:pk>/', update_account, name='update-account'),
    path('baseuser', baseuser),

    path('grooming/', grooming, name='grooming'),
    path('pethostel/', pethostel, name='pet-hostel'),
    path('vaccine/', vaccine, name='vaccination'),

    path('notifications/', notification_view, name='notifications'),
    path('delete/<str:pk>/', notification_delete, name='delete'),

    path('create-message', message_view, name='create-message'),
    path('manage-messages/', manageMessages, name='manage-message'),
    path('delete-message/<int:pk>/', deleteMessage, name='delete-message'),

    path('orderhistory/<int:pk>/', order_history, name='orderhistory'),

]

# appending to the list
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
from django.db import models
from cart.models import Order
from customer.models import Customer
from django.contrib import admin
# Create your models here.

class Shipping(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    city = models.CharField(max_length=200, null=True)
    address = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return self.address

class ShippingAdmin(admin.ModelAdmin):
    list_display = ('customer', 'order', 'city', 'address', 'date_added')
admin.site.register(Shipping, ShippingAdmin)

owner/models.py
from django.db import models

# Create your models here.

owner/views.py
from itertools import product
from multiprocessing import context
from django.shortcuts import render, redirect
from cart.models import *
from customer.forms import *
from products import *
from checkout import *
from products.forms import *
from cart.forms import *
from checkout.forms import *
import datetime
from contact.models import *
from contact.views import *
from firstpro.decorators import *
from django.contrib.auth.decorators import login_required

@login_required(login_url='login')
@admin_restricted
def delete_shipping_order(request, pk):
    order = OrderProduct.objects.get(id=pk)
    if request.method == 'POST':
        order.delete()
        return redirect('/owner-orders/')
    context = {}
    return render(request, 'owner/delete_shipping.html', context)

@login_required(login_url='login')
@admin_restricted
def delete_shipping_order(request, pk):
    order = OrderProduct.objects.get(id=pk)
    order.delete()
    return redirect('/owner-orders/')

@login_required(login_url='login')
@admin_restricted
def manageCustomer(request):
    customer = Customer.objects.all()
    context = {'customers': customer}
    return render(request, 'owner/manage_customer.html', context)

@login_required(login_url='login')
@admin_restricted
def updateCustomer(request, pk):
    customer = Customer.objects.get(id=pk)
    user = request.user
    form = CustomerForm(request.POST)
    if request.method == 'POST':
        customer.name = request.POST.get('name')
        customer.email = request.POST.get('email')
        customer.phone = request.POST.get('phone')
        customer.reward_point = request.POST.get('reward_point')
        username = request.POST.get('username')
        password = request.POST.get('password')
        if password != customer.password:
            if username != customer.username:
                user.username = username
                user.set_password(password)
                user.save()
                customer.password = password
                customer.username = username
        customer.save()
        return redirect('/manage-customer/')
    context = {'form': form, 'customer': customer}
    return render(request, 'owner/updateCustomer.html', context)


# def deleteCustomer(request, pk):
#     customer = Customer.objects.get(id=pk)
#     if request.method == 'POST':
#         customer.delete()
#         return redirect('/manage-customer/')
#     context = {'customer': customer}
#     return render(request, 'owner/deleteCustomer.html', context)

@login_required(login_url='login')
@admin_restricted
def manageProduct(request):
    product = Product.objects.all()
    context = {'products': product}
    return render(request, 'owner/manageProduct.html', context)

@login_required(login_url='login')
@admin_restricted
def deleteCustomer(request, pk):
    customer = Customer.objects.get(id=pk)
    customer.delete()
    return redirect('/manage-customer/')

@login_required(login_url='login')
@admin_restricted
def updateProduct(request, pk):
    product = Product.objects.get(id=pk)
    category = Category.objects.all()
    subCategory = NewSubCategory.objects.all()
    form = ProductForm(request.POST, request.FILES)
    imageform = ImageForm(request.POST, request.FILES, instance=product)
    if request.method == 'POST':
        imageform = ImageForm(request.POST, request.FILES, instance=product)
        product.title = request.POST.get('title')
        product.price = request.POST.get('price')
        product.description = request.POST.get('description')
        category_id = request.POST.get('category')
        category_object = Category.objects.get(id=category_id)
        subcategory_id = request.POST.get('subcategory')
        subcategory_object = NewSubCategory.objects.get(id=subcategory_id)
        product.category = category_object
        product.subcategory = subcategory_object
        product.stock_quantity = request.POST.get('stock_quantity')
        product.type = request.POST.get('type')
        product.purpose = request.POST.get('purpose')
        product.color = request.POST.get('color')
        product.material = request.POST.get('material')
        product.dimensions = request.POST.get('dimensions')
        product.save()
        imageform.save()
        return redirect('/manage-product/')  

    context = {'form': form, 'product': product, 'category': category, 'imageform': imageform, 'subcategory': subCategory}
    return render (request,'owner/updateproduct.html', context )

# def deleteProduct(request, pk):
#     product = Product.objects.get(id=pk)
#     if request.method == 'POST':
#         product.delete()
#         redirect('/manage-product/')
#     context= {'product': product}
    
#     return render(request, 'owner/deleteproduct.html', context)

@login_required(login_url='login')
@admin_restricted
def deleteProduct(request,pk):
    product = Product.objects.get(id=pk)
    product.delete()
    return redirect("/manage-product/")

@login_required(login_url='login')
@admin_restricted
def createOrder(request):
    orderform = OrderForm()
    orderproductform = OrderProductForm()
    checkoutform = ShippingForm()
    customer = Customer.objects.all()
    product = Product.objects.all()
    if request.method == 'POST':
        orderform = OrderForm(request.POST)
        orderproductform = OrderProductForm(request.POST)
        checkoutform = ShippingForm(request.POST)
        orderCustomer = request.POST.get('customer')
        orderProduct = request.POST.get('item')
        orderStatus = request.POST.get('status')
        orderCustomer_object = Customer.objects.get(id=orderCustomer)
        orderProduct_object = Product.objects.get(id=orderProduct)
        order, created = Order.objects.get_or_create(
            customer=orderCustomer_object, order_completed=False, status=orderStatus, order_id=datetime.datetime.now().timestamp())
        order.save()
        order.order_placed = True
        orderQuantity = request.POST.get('quantity')
        orderProduct, created = OrderProduct.objects.get_or_create(
            order=order, item=orderProduct_object, quantity=orderQuantity)
        orderProduct.save()
        checkoutAddress = request.POST.get('address')
        checkoutCity = request.POST.get('city')
        Shipping.objects.create(
            customer=orderCustomer_object,
            order=order,
            city=checkoutCity,
            address=checkoutAddress,

        )
        return redirect('/owner-orders/')
    context = {'customer': customer, 'product': product}
    return render(request, 'owner/createorder.html', context)

@login_required(login_url='login')
@admin_restricted
def updateOrder(request, pk):
    orderform = OrderForm()
    orderproductform = OrderProductForm()
    checkoutform = ShippingForm()
    customer = Customer.objects.all()
    product = Product.objects.all()
    orderProduct = OrderProduct.objects.get(id=pk)
    order = Order.objects.get(id=orderProduct.order.id)
    shipping = Shipping.objects.get(order=order.id)
    orderProduct_item = Product.objects.get(id=orderProduct.item.id)   
    orderCustomer_object = Customer.objects.get(id=order.customer.id) 
    if request.method == 'POST':
        orderform = OrderForm(request.POST)
        orderproductform = OrderProductForm(request.POST)
        checkoutform = ShippingForm(request.POST)
        orderCustomer = request.POST.get('customer')
        orderItem = request.POST.get('item')
        orderStatus = request.POST.get('status')
        updateCustomer_object = Customer.objects.get(id=orderCustomer)
        updateProduct_object = Product.objects.get(id=orderItem)
        order.customer = updateCustomer_object
        order.status = orderStatus
        order.save()
        orderQuantity = request.POST.get('quantity')
        orderProduct.quantity = orderQuantity
        orderProduct.item = updateProduct_object
        orderProduct.save()
        checkoutAddress = request.POST.get('address')
        checkoutCity = request.POST.get('city')
        shipping.address = checkoutAddress
        shipping.city = checkoutCity
        shipping.save()
       
        return redirect('/owner-orders/')
    context = {'customer': customer, 'product': product, 
    'orderProduct': orderProduct,
    'order': order,
    'shipping': shipping,
    'orderProduct_item': orderProduct_item, 
    'orderCustomer': orderCustomer_object}
    return render(request, 'owner/updateOrder.html', context)

@login_required(login_url='login')
@admin_restricted
def manageMessages(request):
    messages = Contact.objects.all()
    context = {'messages': messages}
    return render(request, "owner/messages.html", context)

@login_required(login_url='login')
@admin_restricted
def deleteMessage(request,pk):
    contact = Contact.objects.get(id=pk)
    contact.delete()
    return redirect("/manage-message/")

templates/owner/admin.html
{%extends 'rootpage.html'%}
{% load static %}
{%block content%}

<div class="container-fluid">
    <div class="row">
        <div style="margin-bottom: 30px;">
            <p style="font-size: 22; margin-top: 15px;">

            </p>
        </div>

        <div class="col-lg-2 p-0 sidebar" style="background-color: white; min-height: 100vh;">
            <aside> 
                <ul class="list-group">


                    <li class="list-group-item list-group-item-action {% if request.path == "/owner-orders/" %} bg-primary text-light {% endif %}" >
                        <a href="{% url 'owner-orders' %}" style="text-decoration: none;">
                            <p style="color: black;" class=" {% if request.path == "/owner-orders/" %} text-light {% endif %}">
                                Orders
                            </p>
                        </a>
                    </li>
                    <li class="list-group-item list-group-item-action {% if request.path == "/manage-customer/" %} bg-primary text-light {% endif %}">
                        <a href="{% url 'manage-customer'%}" style="text-decoration: none;">
                            <p style="color: black;"  class=" {% if request.path == "/manage-customer/" %} text-light {% endif %}">
                                Customers
                            </p>
                        </a>
                    </li>
                    <li class="list-group-item list-group-item-action {% if request.path == "/manage-product/" %} bg-primary {% endif %}"  >
                        <a href="{% url 'manage-product'%}" style="text-decoration: none;">
                            <p style="color: black;" class=" {% if request.path == "/manage-product/" %} text-light {% endif %}">
                                Products
                            </p>


                        </a>
                    </li>
                    <li class="list-group-item list-group-item-action {% if request.path == "/manage-message/" %} bg-primary {% endif %}"  >
                        <a href="{% url 'manage-message'%}" style="text-decoration: none;">
                            <p style="color: black;" class=" {% if request.path == "/manage-message/" %} text-light {% endif %}">
                                Messages
                            </p>


                        </a>
                    </li>
                </ul>

            </aside>
        </div>

        <div class="col-lg-10  p-3 body-content" style="min-height: 100vh;">

            <div class="col-lg-  8">
                <span>Hello, {{request.user}}</span>

            </div>
            {%block admincontent%}
            {%endblock admincontent%}

        </div>

    </div>
</div>
{%endblock content%}

templates/owner/admin_orders.html
{% extends 'owner/admin.html' %}

{%load static%}
{%block admincontent%}
<h1 style="font-family: Arial, Helvetica, sans-serif; font-size: 23px; display: inline;">
    Orders
</h1>
<a style="padding-left: 800px; display: inline;" href="{% url 'create-order' %}"><button class="btn btn-primary text-right"> Add Order</button></a>
<br>
<br>
<div class="table-responsive">
    <table class="table table-bordered bg-light" >
        <thead class="thead-dark ">
            <tr>
                <th>customer</th>
                <th>order</th>
                <th>city</th>
                <th>Shipping Address</th>
                <th>date_added</th>
                <th>order id</th>
                <th>status</th>
                <th>quantity</th>
                
                <th>update</th>
                <th>remove</th>

            </tr>
        </thead>

        <tbody>


            {%for i in orders_products%}
            <tr>
                <td>{{i.order.customer}}</td>
                <td>{{i.item.title}}</td>
                {%for j in i.order.shipping_set.all%}
                {%if j %}
                <td>{{j.city}}</td>
                <td>{{j.address}}</td>
                <td>{{j.date_added}}</td>
                {%else%}
                <td></td>
                
                
                <td></td>
                <td></td>
                {%endif%}


                {%endfor%}
                <td>{{i.order.order_id}}</td>
                <td>{{i.order.status}}</td>
                <td>{{i.quantity}}</td>

                <td><a class="btn btn-sm btn-info" href="{% url 'update-order' i.id %}">Update</a></td>
                <td><button class="btn btn-sm btn-danger" data-bs-toggle="modal"
                    data-bs-target="#exampleModal">Remove</button></td>

        </tr>
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Delete?</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Are you sure?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                        <a href="/owner/delete-orders/{{i.id}}" type="submit" class="btn btn-danger">Delete</a>
                    </div>
                </div>
            </div>

            {%endfor%}






        </tbody>

      

    </table>
</div>


{%endblock admincontent%}

templates/owner/createorder.html
{% extends 'rootpage.html' %}
{%load static%}
{% block content%}
<div>
    <br>
    <h1 style="padding-left: 350px;" id="login-header">
        Add Order
    </h1>
    
    
    <div class="form-group" style="width: 950px;">
        <div style="width: 800px">
            <hr>
    
        </div>
        
        <form action="" method="post" enctype="multipart/form-data">
            {%csrf_token%}
            <div style="display: flex; align-items: stretch;">
                <div class="form-field" style="flex: 1;">
                    <label id="login-label">
                        Customer
                    </label>

                    <select class="form-control" id="login-input" name="customer">
                        {% for i in customer%}
                        <option value={{i.id}}>{{i.username}}</option>
                        {%endfor%}
                    </select>
                </div>
                <br>
                <div class="form-field" style="flex: 1;">
                    <label id="login-label">
                        Product
                    </label>

                    <select class="form-control" id="login-input" name="item">
                        {% for i in product%}
                        <option value={{i.id}}>{{i.title}}</option>
                        {%endfor%}
                    </select>
                </div>

            </div>

            <br>
            <div style="display: flex; align-items: stretch;">
                <div class="form-field" style="flex: 1;">
                    <label id="login-label">
                        Status
                    </label>

                    <select name="status" class="form-control" id="login-input">
                        <option value="Pending">Pending</option>
                        <option value="In Process">In Process</option>
                        <option value="Completed">Completed</option>
    
                    </select>
                </div>
                
                <div class="form-field" style="flex: 1;">
                    <label id="login-label">
                        Quantity
                    </label>

                    <input class="form-control"  id="login-input" type="text" name="quantity" class="form-control" />

             </textarea>
             <br>
                </div>
            </div>
            <br>
            <div style="display: flex; align-items: stretch;">
                <div class="form-field" style="flex: 1;">
                    <label id="login-label">
                        Address
                    </label>

                    <input class="form-control"  id="login-input" type="text" name="address" class="form-control" />
                </div>
                

                <div class="form-field" style="flex: 1;">
                    <label id="login-label">
                        City
                    </label>

                    <input class="form-control"  id="login-input" type="text" name="city" class="form-control" />
                </div>
            </div>
            <br>
            <br>
            <div>
                <input style="margin-top: 8px; margin-left: 200px; width: 130px;" id="login-button" value="Add Order" type="submit" name="submit"
                    class="form-control btn btn-primary mb-2" />
                <button style="margin-left: 10px; " id="login-button" class="btn btn-secondary">Cancel</button>
            </div>
        </form>
    </div>

</div>
{% endblock content%}

templates/owner/deleteCustomer.html
<!-- {% load static %}

<p> Do you want to delete this {{customer}}</p>

<form  method="post">
    {% csrf_token %}
    <input type="submit" value="yes" name="submit">
</form> -->

templates/owner/deleteProduct.html
<!-- {% load static %}

<p> Do you want to delete this {{product}}</p>

<form method="post">
    {% csrf_token %}
    <input type="submit" value="yes" name="submit">
</form> -->

templates/owner/delete_shipping.html
{% load static %}

<p> Do you want to delete this {{product}}</p>

<form method="post">
    {% csrf_token %}
    <input type="submit" value="yes" name="submit">
</form>

templates/owner/manageProduct.html
{% extends 'owner/admin.html' %}

{%load static%}
{%block admincontent%}
<h1 style="font-family: Arial, Helvetica, sans-serif; font-size: 23px; display: inline;">
    Products
</h1>
<a style="padding-left: 800px; display: inline;" href="{% url 'create-product' %}"><button
        class="btn btn-primary text-right"> Add Product</button></a>
<br>
<br>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>id</th>
                <th>title</th>
                <th>price</th>
                <th>image</th>
                <th>description</th>
                <th>category</th>
                <th>Stock</th>
                <th>update</th>
                <th>remove</th>
            </tr>
        </thead>

        <tbody>
            {%for product in products%}
            <tr>

                <td>{{product.id}}</td>
                <td>{{product.title}}</td>
                <td>{{product.price}}</td>
                <td>{{product.image}}</td>
                <td>{{product.description}}</td>
                <td>{{product.category}}</td>
                {% if product.stock_quantity > 0 %}
                <td>In Stock</td>
                {%else%}
                <td>Out of Stock</td>
                {%endif%}
                <td><a class="btn btn-sm btn-info" href="{% url 'update-product' product.id %}">Update</a></td>
                <td><button class="btn btn-sm btn-danger" data-bs-toggle="modal"
                        data-bs-target="#exampleModal">Remove</button></td>

            </tr>
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Delete?</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Are you sure?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                            <a href="/delete-product/{{product.id}}" type="submit" class="btn btn-danger">Delete</a>
                        </div>
                    </div>
                </div>
            </div>

                {%endfor%}
        </tbody>

    </table>


</div>


{%endblock admincontent%}

templates/owner/manage_customer.html
{% extends 'owner/admin.html' %}
{% load static %}
{%block admincontent%}
<h1 style="font-family: Arial, Helvetica, sans-serif; font-size: 23px; display: inline;">
    Customers
</h1>
<a style="padding-left: 800px; display: inline;" href="{% url 'register' %}"><button class="btn btn-secondary"> Add
        Customer</button></a>
<br>
<br>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
               
                <th>id</th>
                <th>name</th>
                <th>email</th>
                <th>phone</th>
                <th>date_created</th>
                <th>Vouchers</th>
                <th>update</th>
                <th>remove</th>
            </tr>
        </thead>

        <tbody>
            {%for customer in customers%}
            <tr>

                <td>{{customer.id}}</td>
                <td>{{customer.name}}</td>
                <td>{{customer.email}}</td>
                <td>{{customer.phone}}</td>
                <td>{{customer.date_created}}</td>
                <td>{{customer.reward_point}}</td>
                <td><a class="btn btn-sm btn-info" href="{% url 'update-customer' customer.id%}">Update</a></td>
                <td><button class="btn btn-sm btn-danger" data-bs-toggle="modal"
                    data-bs-target="#exampleModal">Remove</button></td>

        </tr>
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Delete?</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Are you sure?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                        <a href="/delete-customer/{{customer.id}}" type="submit" class="btn btn-danger">Delete</a>
                    </div>
                </div>
            </div>

            {%endfor%}
        </tbody>

    </table>
    
</div>
{%endblock admincontent%}

templates/owner/messages.html
{% extends 'owner/admin.html' %}

{%load static%}
{%block admincontent%}
<h1 style="font-family: Arial, Helvetica, sans-serif; font-size: 23px; display: inline;">
    Products
</h1>
<a  style="padding-left: 800px; display: inline;" href="{% url 'create-product' %}"><button class="btn btn-primary text-right"> Add Product</button></a>
<br>
<br>
<div class="table-responsive">
    <table class="table ">
        <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Message</th>
                <th>remove</th>
            </tr>
        </thead>

        <tbody>
            {%for message in messages%}
            <tr>

                <td>{{message.id}}</td>
                <td>{{message.name}}</td>
                <td>{{message.message}}</td>
               
        
                <td><button class="btn btn-sm btn-danger" data-bs-toggle="modal"
                        data-bs-target="#exampleModal">Remove</button></td>

            </tr>
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Delete?</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Are you sure?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                            <a href="/delete-message/{{message.id}}" type="submit" class="btn btn-danger">Delete</a>
                        </div>
                    </div>
                </div>

                {%endfor%}
        </tbody>

    </table>


</div>


{%endblock admincontent%}